default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  postmark_api_token: <%= ENV["POSTMARK_API_TOKEN"] %>

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

production:
  <<: *default
