concurrency: <%= ENV.fetch('WORKER_PROCESSES', 1) %>

queues:
  - <%= ENV["SQS_DEVELOPERS_DAILY_RECONCILIATION_QUEUE_NAME"] %>
  - <%= ENV["SQS_VEHICLES_DAILY_POPULATE_DATA_QUEUE_NAME"] %>
  - <%= ENV["SQS_VEHICLES_QUARTERLY_POPULATE_DATA_QUEUE_NAME"] %>
  - <%= ENV["SQS_EXPIRED_USER_INVITATION_QUEUE_NAME"] %>
  - <%= ENV["SQS_SEND_EMAILS_TO_DEVELOPERS_QUEUE_NAME"] %>
  - <%= ENV["SQS_SEND_ACTIVATION_EMAIL_QUEUE_NAME"] %>
  - <%= ENV["SQS_DELETE_HANDLE_OBU_JOBS_QUEUE_NAME"] %>
  - <%= ENV["SQS_PROCESS_OBU_FILE_JOB_QUEUE_NAME"] %>
  - <%= ENV["SQS_TASK_RUNNER_QUEUE_NAME"] %>
  - <%= ENV["SQS_SEND_EMAILS_FROM_EMAIL_LIST_QUEUE_NAME"] %>


groups:
  high_priority_group:
    concurrency: <%= ENV.fetch('HIGH_WORKER_PROCESSES', 3) %>
    queues:
      - <%= ENV['SQS_SEND_KEY_TO_DEVELOPER_QUEUE_NAME'] %>
      - <%= ENV["SQS_CREATE_UPDATE_VEHICLE_QUEUE_NAME"] %>
