source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '7.0.0'
# Use postgresql as the database for Active Record
# gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem "puma", "6.3.1"
# Use SCSS for stylesheets
gem "sassc", "~> 2.4.0"
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 4.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false
#Track changes to your models, for auditing or versioning
# gem 'image_processing'
gem 'rubyzip', '2.3.2'
gem 'rack-attack', '6.5.0'

# Manages application of security headers with many safe defaults
gem 'secure_headers', '6.3.3'

group :development, :test do
  gem 'pry'
  gem 'progress_bar', '1.3.0'
end

group :development, :test, :staging do
  gem 'dotenv-rails', '2.7.6'
  gem 'faker', '2.19.0'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '2.1.1'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'brakeman'
  gem 'bundle-audit'
  gem 'yard', '0.9.34'
end

group :test do
  gem 'rspec-rails', '5.0.2'
  gem 'factory_bot_rails', '6.2.0'
  gem 'simplecov', '0.21.2'
  gem 'rubocop', '1.20.0', require: false
  gem 'rubocop-checkstyle_formatter', '0.5.0', require: false
  gem 'rails-controller-testing'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'quartz'
gem 'rainbow'